name: Full Test (NPU)

on:
  pull_request:
    branches:
      - main
      - testcases-260813
    paths:
      - ".github/workflows/full-test-npu.yml"
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or SHA) to test. If not provided, uses the default branch.'
        required: false
        type: string
        default: ''
      job_filter:
        description: 'Select which job to run (leave empty or "all" to run all jobs)'
        required: false
        type: string
        default: 'all'
      image_a3:
        description: 'The a3 running docker image of the test task.'
        required: false
        type: string
        default: 'swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:main-cann9.0.0-a3'
      skip_install_flag:
        description: 'Indicates whether to skip the installation of sglang, defaulting to false.'
        required: false
        type: string
        default: 'false'

concurrency:
  group: full-test-npu-${{ inputs.ref || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'workflow_call' }}

jobs:
  set-image-config:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-vars.outputs.ref }}
      job_filter: ${{ steps.set-vars.outputs.job_filter }}
      image_a3: ${{ steps.set-vars.outputs.image_a3 }}
      skip_install_flag: ${{ steps.set-vars.outputs.skip_install_flag }}
    steps:
      # When triggered by PR, no inputs parameters are used. The latest community code is tested by default.
      - name: Set image config
        id: set-vars
        run: |
          if [ -z "${{ inputs.ref }}" ]; then
            echo "ref=" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ inputs.ref }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.job_filter }}" ]; then
            echo "job_filter=all" >> $GITHUB_OUTPUT
          else
            echo "job_filter=${{ inputs.job_filter }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.image_a3 }}" ]; then
            echo "image_a3=swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:main-cann9.0.0-a3" >> $GITHUB_OUTPUT
          else
            echo "image_a3=${{ inputs.image_a3 }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.skip_install_flag }}" ]; then
            echo "skip_install_flag=false" >> $GITHUB_OUTPUT
          else
            echo "skip_install_flag=${{ inputs.skip_install_flag }}" >> $GITHUB_OUTPUT
          fi

#  nighly-test-npu:
#    needs: [set-image-config]
#    name: nightly-test-npu
#    if: ${{ (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') }}
#    uses: ./.github/workflows/nightly-test-npu.yml
#    with:
#      ref:  ${{ needs.set-image-config.outputs.ref }}
#      job_filter: ${{ needs.set-image-config.outputs.job_filter }}
#      image_a3: ${{ needs.set-image-config.outputs.image_a3 }}
#      skip_install_flag: ${{ needs.set-image-config.outputs.skip_install_flag }}
#    secrets: inherit

  nightly-poc-single-node-tests:
    name: single-node-poc
    if: ${{ !cancelled() }}
    needs: [set-image-config]
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        test_config:
          - name: dynamic_chunking
            runner: linux-aarch64-a3-2
            test_case: test/registered/npu/basic_function/memory_and_scheduling/test_npu_dynamic_chunking.py
          - name: retraction_policy
            runner: linux-aarch64-a3-2
            test_case: test/registered/npu/basic_function/memory_and_scheduling/test_npu_retraction_policy.py
          - name: image_processor_backend
            runner: linux-aarch64-a3-2
            test_case: test/registered/npu/basic_function/optimization_debug_options/test_npu_image_processor_backend.py
          - name: swa_full_tokens_ratio
            runner: linux-aarch64-a3-16
            test_case: test/registered/npu/basic_function/memory_and_scheduling/test_npu_swa_full_tokens_ratio.py
          - name: disable_hybrid_swa_memory
            runner: linux-aarch64-a3-16
            test_case: test/registered/npu/basic_function/memory_and_scheduling/test_npu_disable_hybrid_swa_memory.py
    uses: ./.github/workflows/nightly-test-npu-e2e-single-node.yml
    with:
      runner: ${{ matrix.test_config.runner }}
      test_type: ${{ matrix.test_config.test_type }}
      test_config_name: ${{ matrix.test_config.name }}
      test_case: ${{ matrix.test_config.test_case }}
      image: ${{ needs.set-image-config.outputs.image_a3 }}
      install_sglang_from_source: false
      transformers_version: ''
