name: Full Test (NPU)

on:
  pull_request:
    branches:
      - main
      - testcases-260813
    paths:
      - ".github/workflows/full-test-npu.yml"
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or SHA) to test. If not provided, uses the default branch.'
        required: false
        type: string
        default: ''
      job_filter:
        description: 'Select which job to run (leave empty or "all" to run all jobs)'
        required: false
        type: string
        default: 'all'
      image_a3:
        description: 'The a3 running docker image of the test task.'
        required: false
        type: string
        default: 'swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:main-cann9.0.0-a3'
      skip_install_flag:
        description: 'Indicates whether to skip the installation of sglang, defaulting to false.'
        required: false
        type: string
        default: 'false'

concurrency:
  group: full-test-npu-${{ inputs.ref || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'workflow_call' }}

jobs:
  set-image-config:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-vars.outputs.ref }}
      job_filter: ${{ steps.set-vars.outputs.job_filter }}
      image_a3: ${{ steps.set-vars.outputs.image_a3 }}
      skip_install_flag: ${{ steps.set-vars.outputs.skip_install_flag }}
    steps:
      # When triggered by PR, no inputs parameters are used. The latest community code is tested by default.
      - name: Set image config
        id: set-vars
        run: |
          if [ -z "${{ inputs.ref }}" ]; then
            echo "ref=" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ inputs.ref }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.job_filter }}" ]; then
            echo "job_filter=all" >> $GITHUB_OUTPUT
          else
            echo "job_filter=${{ inputs.job_filter }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.image_a3 }}" ]; then
            echo "swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:main-cann9.0.0-a3" >> $GITHUB_OUTPUT
          else
            echo "image_a3=${{ inputs.image_a3 }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.skip_install_flag }}" ]; then
            echo "skip_install_flag=false" >> $GITHUB_OUTPUT
          else
            echo "skip_install_flag=${{ inputs.skip_install_flag }}" >> $GITHUB_OUTPUT
          fi
  nighly-test-npu:
    needs: [set-image-config]
    name: nightly-test-npu
    if: ${{ (github.repository == 'sgl-project/sglang' || github.event_name == 'pull_request') }}
    uses: ./.github/workflows/nightly-test-npu.yml
    with:
      ref:  ${{ needs.set-image-config.outputs.ref }}
      job_filter: ${{ needs.set-image-config.outputs.job_filter }}
      image_a3: ${{ needs.set-image-config.outputs.image_a3 }}
      skip_install_flag: ${{ needs.set-image-config.outputs.skip_install_flag }}
    secrets: inherit

  full-test-npu-perf-16:
    name: full-test-npu
    if: ${{ !cancelled() }}
    needs: [set-image-config]
    uses: ./.github/workflows/_npu-single-node-test-stage.yml
    with:
      runner: linux-aarch64-a3-16
      test_type: 'perf'
      test_suite: full-test-npu-perf-16
      is_nightly_pipeline_job: true
      skip_pr_test_health_check: 'true'
      image: ${{ needs.set-image-config.outputs.image_a3 }}
      install_sglang_deps: false
      device_type_for_deps: 'a3'
      run_start_metadata: ${{ needs.set-image-config.outputs.run_start_metadata }}
